### PR TITLE
PHP 7.4 and higher, dropped old dependencies, GitHub Actions

### LINKED ISSUE #46: Fatal error after calling setLogger
https://github.com/alchemy-fr/BinaryDriver/blob/e0615cdff315e6b4b05ada67906df6262a020d22/src/Alchemy/BinaryDriver/ProcessRunner.php#L43

A new bug appeared with the recent update of psr/log v3. The ProcessRunnerInterface from psr/log version 3 provides a setLogger function that returns a `void`. PHP 8.0.12 now enforce that you declare the right return type when implementing interfaces. 

As it currently return a ProcessRunner, I end up with this error when using it : 
`Declaration of Alchemy\BinaryDriver\ProcessRunner::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void`

Either return a void to comply to the interface, either get back to psr/log version 1 that doesn't provide any return type

### PR DESCRIPTION
**Pull request by pascalbaljet**
* Support for PHP 7.4, 8.0 and 8.1 (GitHub Actions)
* Dropped support for PHP 7.3 and lower
* Support for `psr/log` 2.0 and 3.0
* Support for `symfony/process` 6.0
* Dropped support for `symfony/process` 4.0 and lower
* Dropped support for `ProcessBuilder` as it was removed in Symfony 4.

GitHub Actions run: https://github.com/protonemedia/BinaryDriver/actions/runs/1602252938

Closes #46

### CODE REVIEW

**Comment by secit-pl** [comment]
+1 for this as it's currently not possible to use this bundle with latest Symfony

**Comment by vanthao03596** [comment]
merge ?

**Comment by secit-pl** [comment]
any update on this?

**Comment by pascalbaljet** [comment]
I've opened a PR at the php-ffmpeg repo to integrate this package:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/849

**Pull request closed without merging**
