### PR TITLE
Make monolog optional

### PR DESCRIPTION
**Pull request by alexander-schranz**
Remove requirement to monolog by using the PSR NullLogger as fallback

### CODE REVIEW

**Comment by pascalbaljet** [comment]
Could you publish a new tag with this PR? This repo currently blocks projects that requires Monolog 2.

**Comment by alexander-schranz** [comment]
@pascalbaljet  I'm not a maintainer I'm also waiting for it 😆

**Comment by jens1o** [comment]
I'd rather land this change in the `v1.x` tree, where we already did this change. I don't think this would not be a breaking change.

**Comment by alexander-schranz** [comment]
@jens1o sorry doesn't make any sense for me that this is in 1.x but not in 5.x, it should really be in the newest version of the binary and its not a breaking change as no public function define to return a monolog instance there is always psr defined.

**Comment by nnatter** [comment]
Can we find a solution here? This package currently blocks me from updating to Monolog 2.

**Pull request closed without merging**
